services:
  - type: web
    name: tcc-backend
    env: docker
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_SSL_MODE
        value: require
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRATION_MS
        value: "2592000000"
      - key: CORS_ALLOWED_ORIGIN_PATTERNS
        sync: false
      - key: JPA_DDL_AUTO
        value: update
      - key: JPA_SHOW_SQL
        value: "false"
